### ISSUE TITLE
Not running latest design

### ISSUE THREAD

**Issue by darbotlabs** [darbotlabs/Darbot-Agent-Engine#3]
This version on github hasn't been updated with the Retro Cyber Modern Fluent design yet 

Implement the updated design throughout the app, then perform full functionality audit to ensure no regressions after design update is complete

# Darbot Agent Engine — Cyber‑Retro × Fluent 2 Style Guide (Bulma Edition)

> **Version:** 1.0  | **Updated:** 2025‑05‑27
> **Scope:** Fork of Microsoft **Multi‑Agent Custom Automation Engine** → now **Darbot Agent Engine**
> **Stacks:** Bulma CSS ≥ 0.9, Font Awesome 6, Vanilla JS, HTML5
> **Goal:** Provide a *single source of truth* so every page, component, and PR adheres to a consistent Darbot Labs look‑and‑feel.

---

## 1 • Core Design Principles

|  Principle         |  What it means for Darbot Agent Engine               |
| ------------------ | ---------------------------------------------------- |
| **Cyber‑Retro**    | Neon accents, dark CRT‑style surfaces, mild glow.    |
| **Fluent 2**       | 12 px radii, acrylic «glass», depth & subtle motion. |
| **Bulma Harmony**  | Use Bulma variables + helpers; extend, don’t fight.  |
| **Modern Minimal** | Clear hierarchy, 8‑pt grid, zero ornamental noise.   |

---

### 2.1 Tokens & Bulma Vars

Add to \`\` (import *after* `bulma.css`) and reference everywhere.

```css
:root {
  /* Brand gradient */
  --g-start:#b54cff;  /* Darbot purple */
  --g-mid:#0078ff;    /* Nitrous blue  */
  --g-end:#00e0b4;    /* Teal accent   */

  --primary:#464feb;          /* Legacy primary (Bulma $primary) */
  --success:#1db954;          /* Bulma $success  override        */
  --warning:#ffb020;          /* Bulma $warning  override        */
  --danger: #ff4d4f;          /* Bulma $danger   override        */

  --bg-surface:#0e0f13;       /* Dark surface for app chrome     */
  --bg-page:#f7f9fb;          /* Light page background (light UI)*/
  --txt-main:#222831;         /* Dark text on light areas        */
  --txt-main-dark:#f4f4f6;    /* Light text on dark areas        */
  --txt-sub:#6b7280;          /* Muted gray                      */
}

/* Sync Bulma colors */
$primary:   var(--primary);
$success:   var(--success);
$warning:   var(--warning);
$danger:    var(--danger);
```

`BrandGradient` utility:

```css
.gradient-bg {
  background:linear-gradient(135deg,var(--g-start) 0%,var(--g-mid) 40%,var(--g-end) 100%);
}
```

### 2.2 Theme Modes

* **Light Default** — page bg `--bg-page`, cards use lighter acrylic (#FFF → #F F).
* **Dark Mode** — toggle `<body class="is-dark">`; switch variables via `[data-theme="dark"]` attribute (see *theme.css* template).

---

## 3 • Typography

| Role      | CSS           | Size (rem) | Weight |
| --------- | ------------- | ---------- | ------ |
| Display‑1 | `.title.is-1` | 2.25       | 600    |
| Heading‑2 | `.title.is-3` | 1.75       | 600    |
| Body      | `.content p`  | 1.00       | 400    |
| Small     | `.is-size-7`  | 0.875      | 400    |
| Code/Mono | `pre, code`   | 0.875      | 400    |

**Stack:** `Segoe UI`, `Inter`, system‑ui.

```css
html {font-family:'Segoe UI',Tahoma,Verdana,sans-serif;}
```

---

## 4 • Spacing & Layout Grid

* **8‑pt grid** across padding/margins.
* Bulma helpers (`m‑?‑X`, `p‑?‑X`) still map to 0.25 × `rem`; keep multiples of 4 px.

```scss
$gap:16px; // Bulma column gap => 8‑pt step
```

**Custom spacing tokens** (optional):

```css
:root{ --s-1:4px; --s-2:8px; --s-3:12px; --s-4:16px; --s-5:24px; --s-6:32px; }
```

---

## 5 • Corner Radius

| Token           | Value                   |
| --------------- | ----------------------- |
| `--radius-lg`   | 12 px (cards, modals)   |
| `--radius-md`   | 8 px  (buttons, inputs) |
| `--radius-pill` | 999 px (status bullets) |

```css
.card, .modal-card {border-radius:var(--radius-lg);}
.button           {border-radius:var(--radius-md);}
.status-dot       {border-radius:var(--radius-pill);}
```

---

### 6.1 Buttons

| Variant                    | Class                                        | Style Rules                                              |
| -------------------------- | -------------------------------------------- | -------------------------------------------------------- |
| Primary                    | `.button.is-primary.gradient`                | `@extend .gradient-bg; color:#fff;`                      |
| Secondary                  | `.button.is-light`                           | border `1px solid var(--primary)`; text `var(--primary)` |
| Ghost                      | `.button.is-text`                            | Transparent; underline on hover                          |
| Success / Warning / Danger | Inherit Bulma color + gradient fade on hover |                                                          |

```scss
.button.gradient{
  @extend .gradient-bg;
  &:hover{filter:brightness(1.1);}
}
```

### 6.2 Agent Avatar w/ Status

```html
<span class="avatar is-32">
  <img src="agent.png" alt="Agent" />
  <span class="status-dot is-success"></span>
</span>
```

```css
.avatar{position:relative;display:inline-block;width:32px;height:32px;border-radius:50%;overflow:hidden;}
.status-dot{position:absolute;bottom:-2px;right:-2px;width:10px;height:10px;background:var(--success);box-shadow:0 0 4px var(--success);}
```

### 6.3 Task Card

```html
<div class="card task-card">
  <header class="card-header gradient-bg">
     <p class="card-header-title">Task #42</p>
  </header>
  <div class="card-content">…</div>
</div>
```

* Top header uses gradient; body acrylic via `background:var(--card-bg); backdrop-filter:blur(14px)`.

### 6.4 Progress Stages

`<progress class="progress is-small is-primary" value="35" max="100"></progress>`

* Override Bulma `.progress` background with gradient.

### 6.5 Modal Dialogs

* `.modal-card` width 640 px, radius 12 px, dark acrylic background in dark mode.
* Include **motion**: scale 0.96 → 1 with 120 ms ease‑out.

### 6.6 Navigation Sidebar

* Bulma `.menu`; active link gradient pill (`border-radius:var(--radius-pill);`).

---

## 7 • Effects & Motion

| Effect           | CSS                                                                     | Notes                         |
| ---------------- | ----------------------------------------------------------------------- | ----------------------------- |
| Acrylic Glass    | `background:var(--card-bg); backdrop-filter:blur(14px) saturate(160%);` | Use on `.card`, `.modal-card` |
| Hover Brightness | `filter:brightness(1.08)`                                               | Buttons, cards                |
| Focus Ring       | `outline:2px solid var(--g-end); outline-offset:2px;`                   |                               |
| Shimmer Loader   | Keyframe gradient shift across `--g-start → --g-end` every 2 s          |                               |

---

## 8 • Accessibility & HC

* **Contrast:** ensure ≥ 4.5 : 1 on body text vs surface.
* **Prefers‑reduced‑motion:** disable shimmer + scale anim.

```css
@media (prefers-reduced-motion:reduce){
  *{transition:none!important;}
  .shimmer{animation:none!important;}
}
```

---

## 9 • Code & File Conventions

| Area                | Convention                                               |
| ------------------- | -------------------------------------------------------- |
| **SCSS vars**       | `$dbe-*` prefix for custom tokens.                       |
| **Component files** | `components/_task-card.scss`, `components/_avatar.scss`. |
| **JS modules**      | kebab‑case filenames; PascalCase class names.            |
| **Bulma overrides** | Keep in `theme.scss`; avoid editing `bulma.sass`.        |

---

## 10 • Implementation Checklist

*

---

*Crafted with ❤︎ by Darbot Labs · Contact ****@DesignOps**** for reviews or additions.*
